// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFILh1_qoRtr1KhIAkZTMNvYYxb1jRFvg',
    appId: '1:469061446199:android:80b0254a3ed07aacf22db2',
    messagingSenderId: '469061446199',
    projectId: 'ticketing-app-sbm',
    storageBucket: 'ticketing-app-sbm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpkg8njVbuWmAQqYwVyyTHjJ2H-yC9eb4',
    appId: '1:469061446199:ios:fcf8d994573ef004f22db2',
    messagingSenderId: '469061446199',
    projectId: 'ticketing-app-sbm',
    storageBucket: 'ticketing-app-sbm.firebasestorage.app',
    iosClientId: '469061446199-m1qsgi2kteds61lrtgukgm9kj9seclb4.apps.googleusercontent.com',
    iosBundleId: 'com.ticketing.sbm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpkg8njVbuWmAQqYwVyyTHjJ2H-yC9eb4',
    appId: '1:469061446199:ios:068fa620e3b1ed5cf22db2',
    messagingSenderId: '469061446199',
    projectId: 'ticketing-app-sbm',
    storageBucket: 'ticketing-app-sbm.firebasestorage.app',
    iosBundleId: 'com.example.ticketingAppSbm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAxjkKGJXgst32oY0WGWV_dOhIU7R2rW0',
    appId: '1:469061446199:web:8b4e2d1d7d2a30d3f22db2',
    messagingSenderId: '469061446199',
    projectId: 'ticketing-app-sbm',
    authDomain: 'ticketing-app-sbm.firebaseapp.com',
    storageBucket: 'ticketing-app-sbm.firebasestorage.app',
    measurementId: 'G-S2WNJKS943',
  );

}